#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace $rootnamespace$.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class RazorView : PortableRazor.ViewBase
{

#line hidden

#line 2 "RazorView.cshtml"
public $rootnamespace$.Models.Model1 Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\n<html>\n<head>\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"style.css\"");

WriteLiteral(" />\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\n        // This javascript method is called from C#\n        function SetLabelTe" +
"xt(text) {\n            var elm = document.getElementById(\'label\');\n            e" +
"lm.innerHTML = text;\n        }\n    </script>\n</head>\n<body>\n");


#line 18 "RazorView.cshtml"
    

#line default
#line hidden

#line 18 "RazorView.cshtml"
     using (@Html.BeginForm("UpdateLabel", "Controller1", new { val = @Model.Value })) {



#line default
#line hidden
WriteLiteral("        <h4");

WriteLiteral(" id=\"label\"");

WriteLiteral(">");


#line 20 "RazorView.cshtml"
                  Write(Model.Text);


#line default
#line hidden
WriteLiteral("</h4>\n");


#line 21 "RazorView.cshtml"

        

#line default
#line hidden

#line 22 "RazorView.cshtml"
   Write(Html.TextBox("val", @Model.Value));


#line default
#line hidden

#line 22 "RazorView.cshtml"
                                           



#line default
#line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Update Label\"");

WriteLiteral(" />\n");


#line 25 "RazorView.cshtml"
    }


#line default
#line hidden
WriteLiteral("\n    <br/><span");

WriteLiteral(" id=\"CustomToolWarning\"");

WriteLiteral(" style=\"color:orange\"");

WriteLiteral(@">If you are seeing this text, you have not yet run the <b>RazorTemplatePreprocessor CustomTool</b> on this view.<br/>  
    In the property pane for <b>Views/RazorView.cshmtl</b>, set <b>CustomTool</b> to <b>RazorTemplatePreprocessor</b>; otherwise,
    the class generated for for this view will not reflect your changes to <b>RazorView.cshtml</b>.</span><br/>

    <br/><span");

WriteLiteral(" id=\"MissingStyleWarning\"");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(@">
    If you are seeing this text, <b>style.css</b> has not been copied into webroot on your device.<br/>
    In the property pane for <b>Content/style.css</b>, set <b>BuildAction</b> to <b>EmbeddedResource</b> and
    uncomment the ""<i>Initialize static content...</i>"" lines in the <b>Init(IHybridWebView)</b> method in <b>Startup.cs</b>.
    </span>

</body>
</html>	");

}
}
}
#pragma warning restore 1591
